spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/report?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver  # tomcat 8.0+

