spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/report?serverTimezone=CTT&characterEncoding=UTF-8  # 设置字符编码utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver  # tomcat 8.0+
    sql-script-encoding: UTF-8

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

  thymeleaf:
    cache: false  # 页面修改后立即生效，关闭缓存，立即刷新
  devtools:
    restart:
      enabled: true  # 热部署生效
      additional-paths: src/java/main  # 设置需要重启的目录
      exclude: static/**,public/**,WEB-INF/**

  messages:
    basename: msg

#  profiles:
#    active: prod

logging:
  level:
    com.neo: debug
server:
  port: 8080
